SET IDENTITY_INSERT [dbo].[NhaTroes] ON
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (2, N'Hoa Lan, Phường 2, Quận Phú Nhuận, TPHCM', N'72 m2', N'Hoàng Kim', N'0949018998', N'Diện tích: 4x18m. Nhà mới sàn suốt.', N'Nhà nguyên căn 4 lầu hầm. Nhà phù hợp spa, thẩm mỹ, trụ sở văn phòng cty, trung tâm đào tạo, showroom, shop, ở kinh doanh....', N'45 tr/tháng', N'~/Imagess/PN1.png', NULL, 0, N'1900-01-01 00:00:00', N'QPhuNhuan
')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (3, N'Nguyễn Công Hoan p7 Phú Nhuận gần Phan Đăng Lưu ', N'25 m2', N'Phong', N'0812500139', N'Dạng phòng studio đầy đủ tiện nghi', N'Dạng phòng studio có thang máy , hầm xe , camera khoá cổng vân tay an ninh 24/7, Ở được tối đa 3 người, Cửa sổ ban công thoáng', N'5 - 6 triệu/tháng', N'~/Imagess/PN1.1png', NULL, 0, N'1900-01-01 00:00:00', N'QPhuNhuan
')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (4, N' 23 Phan Xích Long , phường 3, quận Phú Nhuận', N'35 m2', N'Mr. Hoàng', N'01628116732', N'Căn Hộ VIP Máy Giặt Riêng - Gần Ngã 4 PHÚ NHUẬN', N'Căn Hộ VIP Máy Giặt Riêng - Gần Ngã 4 PHÚ NHUẬN - Nơi tập trung nhiều khu mua sắm, đặc biệt tấp nập về đêm, gần Q1, Q10', N'6tr5/tháng', N'~/Imagess/PN1.2png', NULL, 0, N'1900-01-01 00:00:00', N'QPhuNhuan
')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (5, N'Lê Văn Sỹ, Phường 11, Quận Phú Nhuận, TPHCM', N'40 m2', N'Mr Hoàng', N'01628116732', N'Căn Hộ Cao Cấp 1PN 1 Phòng Bếp Riêng ', N'Gần sân bay Tân Sơn Nhất, ga Sài Gòn, chợ và siêu thị, thoải mái với nhiều hướng đi mà giờ cao điểm không kẹt xe hay mất nhiều thời gian', N'8 triệu/ tháng', N'~/Imagess/PN1.3png', NULL, 0, N'1900-01-01 00:00:00', N'QPhuNhuan
')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (6, N'Trần Kế Xương, Phường 7, Quận Phú Nhuận, TPHCM', N'20 m2', N'Mr.Khá', N'0935 534 687', N'Phòng mới, thoáng mát, khu an ninh. Gần Phan Xích Long', N'Phòng mới hoàn thiện cho thuê. Các phòng đều có cửa sổ thoáng mát gió tươi vào phòng trang bị sẵn máy lạnh, internet tốc độ cao.', N'2tr5/tháng', N'~/Imagess/PN1.4png', NULL, 0, N'1900-01-01 00:00:00', N'QPhuNhuan
')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (7, N'Đồng Xoài, Phường 13, Quận Tân Bình, TPHCM', N'28 m2', N'Lê Long ', N'01628117888', N'Căn Hộ mới xây có cửa sổ, đầy đủ tiện nghi đối diện Etown 2', N'Phòng mới xây full  nội thất có gác, thang máy, vân tay và máy giặt chung ở tầng trệt', N'4tr/tháng', N'~/Imagess/PN2.1png', NULL, 0, N'1900-01-01 00:00:00', N'QTanBinh')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (8, N'Đường A4, Phường 12, Quận Tân Bình, TPHCM', N'25 m2', N'Khang Nguyễn', N'0855669097', N'Căn hộ có gác full nội thất_k300_Cộng Hòa', N'Trong nội khu dân cư sầm uất lu bù hàng quán ăn ngon triệu view, Thiết kế hiện đại, tối giản, tiện lợi, phù hợp với sinh viên.', N'3tr8/tháng', N'~/Imagess/PN2.2png', NULL, 0, N'1900-01-01 00:00:00', N'QTanBinh')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (9, N'Nhất Chi Mai, Phường 13, Quận Tân Bình, TPHCM', N'25 m2', N'Hữu Khang', N'0855669097', N'Căn hộ quận Tân Bình ngay Etown 2 _ FULL nội thất', N'Thuận tiện đi các quận trung tâm, gần Etown, Trường Chinh, Cộng Hoà,…, Gần khu ăn uống, trung tâm thương mại, siêu thị tiện lợi', N'5tr3/tháng', N'~/Imagess/PN2.3png', NULL, 0, N'1900-01-01 00:00:00', N'QTanBinh')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (10, N'Bình Giã, Phường 13, Quận Tân Bình, TPHCM', N'30 m2', N'Trí Dương', N'0855669097', N'Căn hộ cửa sổ / ban công _ FULL nội thất', N'Thuận tiện đi các quận trung tâm, gần Etown, Trường Chinh, Cộng Hoà, gần khu ăn uống, trung tâm thương mại,siêu thị.', N'5tr/tháng', N'~/Imagess/PN2.4png', NULL, 0, N'1900-01-01 00:00:00', N'QTanBinh')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (11, N'Giải Phóng, Phường 4, Quận Tân Bình, TPHCM', N'20 m2', N'Trí Dương', N'0855669097', N'Căn Hộ Cao Cấp Khu Sân Bay - Tân Bình', N'Đường xe hơi lớn, khu vực an ninh,  yên tĩnh, xung quanh Cửa hàng, siêu thị tiện lợi, Full nội thất, có thang máy, bảo vệ 24/24', N'6tr5/tháng', N'~/Imagess/PN2.5png', NULL, 0, N'1900-01-01 00:00:00', N'QTanBinh')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (12, N'Hoàng Xuân Hoành, Phường Hiệp Tân, Quận Tân Phú, TPHCM', N'25 m2', N'Trí Dương', N'0855669097', N'Căn Hộ Duplex Cao Cấp Quận Tân Phú ', N'Đường xe hơi lớn, khu vực an ninh,  yên tĩnh, xung quanh Cửa hàng, siêu thị tiện lợi, Full nội thất, có thang máy, bảo vệ 24/24', N'3tr5/tháng', N'~/Imagess/PN3.1png', NULL, 0, N'1900-01-01 00:00:00', N'QTanPhu')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (13, N'Khuông Việt, Phường Phú Trung, Quận Tân Phú, TPHCM', N'30 m2', N'Trí Dương', N'0855669097', N'Căn hộ quận Tân Phú _ mô hình Duplex chung cư ', N'Gần công viên, trung tâm thương mại,... tiện ích khỏi bàn. Có siêu thị bên trong toà nhà, giao thông tiện đi lại, thang máy cao cấp', N'5tr5/tháng', N'~/Imagess/PN3.2png', NULL, 0, N'1900-01-01 00:00:00', N'QTanPhu')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (14, N'Vườn Lài, Phường Phú Thọ Hòa, Quận Tân Phú, TPHCM', N'30 m2', N'Trí Dương', N'0855669097', N'HOT NEW 2021 _ căn hộ mới xây _ FULL nội thất cao cấp', N'Full nội thất, có ban công, cửa sổ thoáng mát, rộng có camera giám sát 24/7, khu vực sấy riêng FREE, giờ giấc tự do, dân trí văn minh', N'4tr5/tháng', N'~/Imagess/PN3.3png', NULL, 0, N'1900-01-01 00:00:00', N'QTanPhu')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (15, N'Vườn Lài, Phường Tân Thành, Quận Tân Phú, TPHCM', N'30 m2', N'Trí Dương', N'0855669097', N'Căn hộ MỚI XÂY FULL nội thất cao cấp _ ngay Vườn Lài', N'Con đường khu trung tâm ăn uống của quận Tân Phú. Cách đường Vườn Lài vài chục mét. Cách quận Tân Bình vài trăm mét', N'4tr5/tháng', N'~/Imagess/PN3.4png', NULL, 0, N'1900-01-01 00:00:00', N'QTanPhu')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (16, N'Tân Hương, Phường Tân Quý, Quận Tân Phú, TPHCM', N'20 m2', N'Văn Trinh', N'0908798781', N'Căn hộ có gác siêu xịn', N'Đầy đủ nội thất : tủ lạnh, bàn ghế, tủ bếp,niệm, tủ quần áo. Phòng ở được 3-4ng', N'4tr/tháng', N'~/Imagess/PN3.5png', NULL, 0, N'1900-01-01 00:00:00', N'QTanPhu')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (17, N'Đường số 10, Phường Hiệp Bình Chánh, Quận Thủ Đức, TPHCM', N'90 m2', N'Anh Văn', N'0765568249', N'Opal Riverside full nội thất 3PN,90m2 ', N'Phòng mới xây full  nội thất có gác, thang máy, vân tay và máy giặt chung ở tầng trệt', N'15tr5/tháng', N'~/Imagess/PN4.1png', NULL, 0, N'1900-01-01 00:00:00', N'QThuDuc')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (18, N'Đào Trinh Nhất, Phường Linh Tây, Quận Thủ Đức, TPHCM', N'75 m2', N'Anh Văn', N'0981170149', N'Căn hộ linh tây Tower-75m2,2PN/2WC,Nội thất đầy đủ', N'Gần vinmark, trường học, cafe, gym,... gần ngay tuyến đường phạm văn đồng thuận tiện cho việc di chuyển lên bình thạnh, quận 1', N'10tr/tháng', N'~/Imagess/PN4.2png', NULL, 0, N'1900-01-01 00:00:00', N'QThuDuc')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (19, N'Đường số 3, Phường Trường Thọ, Quận Thủ Đức, TPHCM', N'70 m2', N'Anh Văn', N'0765568249', N'Căn hộ lavita garden, 2PN, Nội thất cao cấp', N'Lầu cao thoáng mát, view đẹp, phù hợp cho gia đình 3-4 người thuê', N'10tr/tháng', N'~/Imagess/PN4.3png', NULL, 0, N'1900-01-01 00:00:00', N'QThuDuc')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (20, N'Đường số 6, Phường Bình Chiểu, Quận Thủ Đức, TPHCM', N'70 m2', N'Anh Văn', N'0835858589', N'Căn hộ tại chung cư Fresca Riverside,70m2,2PN,Nội thất.', N'Gồm 2 phòng ngủ, 2 WC, Sau chợ đầu mối Thủ Đức, view hướng gió, Hướng Đông Nam, phù hợp cho gia đình 4-5 người thuê để ở, gần chợ ', N'8tr/tháng', N'~/Imagess/PN4.4png', NULL, 0, N'1900-01-01 00:00:00', N'QThuDuc')
INSERT INTO [dbo].[NhaTroes] ([IDNha], [Tenduong], [DienTich], [TenChuNha], [SDT], [CTNha], [GioiThieu], [Gia], [image], [diaDiem_IDQuan], [ratting], [DateTime], [IDQuann]) VALUES (21, N'18 Kha Vạn Cân, Phường Linh Trung, TP. Thủ Đức, TPHCM', N'80 m2', N'Anh Văn', N'0981170149', N'Căn hộ 2pn 80m2, nội thất Full opal boulevard ', N'Vị trí gần: Phạm Văn Đồng, Võ Văn Ngân, vincom, ĐH QG, coopmart, Di chuyển nhanh sang: Q2, TĐ, Mất 15'' để đến sân bay Tân Sơn Nhất', N'11tr/tháng', N'~/Imagess/PN4.5png', NULL, 0, N'1900-01-01 00:00:00', N'QThuDuc')
SET IDENTITY_INSERT [dbo].[NhaTroes] OFF
