// <auto-generated />
namespace ThueTro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Datatesst123321 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datatesst123321));
        
        string IMigrationMetadata.Id
        {
            get { return "202107231859456_Datatesst123321"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
